### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lenguyenthedat**
Docker images will need to be built beforehand.
Otherwise:

```
 $ docker run -e REDSHIFT_CONNECTION_STRING="user= password= host= port=5439 dbname=" -p 5000:5000 everythingme/redshift-console
 Unable to find image 'everythingme/redshift-console:latest' locally
 Pulling repository docker.io/everythingme/redshift-console
 Error: image everythingme/redshift-console:latest not found
```

### CODE REVIEW

**Comment by arikfr** [comment]
No need to build the image -- it's available on Docker Hub. The problem was a spelling mistake in the image name, fixed in 90fe5c9720a47d023367b156361f9e60bd4cc6fb.

Thanks for noticing!

**Comment by lenguyenthedat** [comment]
:+1:

btw, is it possible for us to build it with docker from source instead of pulling it from pip? :smile:

**Comment by arikfr** [comment]
@lenguyenthedat for development?

**Comment by lenguyenthedat** [comment]
Yes! I was thinking of some features like displaying historical queries, and users who execute them.

**Comment by arikfr** [comment]
I started working on a Docker image for development. I found out it has bad performance on OS/X and didn't finish it, I pushed it to GitHub if you want to try it out: https://github.com/EverythingMe/redshift_console/pull/22

**Comment by lenguyenthedat** [comment]
:+1:  thanks!

**Pull request closed without merging**
